### ISSUE TITLE
Error 500 on Tau Tracker

### ISSUE THREAD

**Issue by Rowin** [taustation-fan/universal-tau-tracker#17]
When trying to access the distances for Alpha Centauri's (https://tracker.tauguide.de/distance/system/3), the server replies with an error 500.

The other stars are not affected, the pages can be loaded without any issue

**Comment by DBX12** [comment]
I've talked with moritz on Discord about it. If you tell them about the 500, they usually are pretty quick to fix it. Alternatively, you can send them an in game message (link is in the Readme) :)

**Comment by Rowin** [comment]
I've seen that recently on Discord but forgot to update this issue. Thanks !
