### ISSUE TITLE
two ships at docks confuse fuel price tracker

### ISSUE THREAD

**Issue by traktofon** [taustation-fan/universal-tau-tracker#4]
When one has two ships at the docks, the fuel price notification is shown twice. If the ships are different kinds (like razorback and private shuttle) the local fuel price differs strongly between the two notifications, and I believe the wrong data gets recorded.

**Comment by moritz** [comment]
Now the correct data should be recorded in both cases. You'll still get two notifications though, which I'm kinda OK with.
