### ISSUE TITLE
Data model for items: add additional fields?

### ISSUE THREAD

**Issue by traktofon** [taustation-fan/universal-tau-tracker#8]
The [current data model](https://github.com/taustation-fan/universal-tau-tracker/blob/c8d783d9314faf7917e69133801d328013c6bfa2/utt/model.py#L369-L400) for items caters mostly to weapons and armor. Other item categories provide data in additional fields that are currently not considered:

- "Medical" items (stims) have boost stats and toxicity
- "Food" items have fields that could be parsed from the description, e.g. target genotype and affected stat.
- cf. https://github.com/traktofon/tau-utility-scripts/tree/master/items

Do we want to add (some of) this structured data?

**Comment by moritz** [comment]
Good point, we should track those as well.

Oh, and there's a description that we also should store :-)

Now, this `Item` object is starting to accumulate quite some attributes, and I wonder if we should factor out different aspects; like an `ItemWeapon` with weapons aspects, an `ItemFood` for food characteristics etc, and only keep the common attributes (name, description, mass, tier, rarity) in the core Item.

Do you have an opinion on that, @traktofon?

**Comment by traktofon** [comment]
TBH I don't have experience with object-relational data modeling, so I can't tell which approach works better. A thin core `Item` with specialized `ItemWeapon` etc sounds reasonable. Not sure what the tradeoffs are either way.

**Comment by moritz** [comment]
FYI I've gone with separate tables for separate types; so far it seems to work.

I'm closing this issue now, as we have a pretty generic approach to storing more structured item data. If we have specific other things to store, let's have separate issues for those.
