### ISSUE TITLE
WIP: track vendor inventory and items

### ISSUE THREAD

**Issue by traktofon** [taustation-fan/universal-tau-tracker#9]
Opening this issue to discuss what needs to be done to track vendor inventory and items in general.
I think we need to:

- [x] update the userscript to scrape and submit data from item pages and vendor pages
- [x] update the database schema (data model) to store data about items and vendor inventories
- [x] add API endpoints for receiving those data

Some questions:

1. How is time handled? Like fuel price, vendor inventory pricing changes daily. For the fuel price prediction we need to be able to get fuel price and inventory pricing from the same "day". Is a timestamp added by the server, or should it be added in the submitted data?
2. Do we keep historical data, or only the latest?
3. Vendor inventory can differ slightly between players (vip-3 availability), how do we hanlde that?

**Comment by moritz** [comment]
Let me try to answer:

> How is time handled?

Generally the server leads here, because we cannot rely on all clients having a correct time configured.

> Do we keep historical data, or only the latest?

So far, the Tau Tracker's philosophy has been to keep all historical data. If that becomes burdensome in the future, we can later add some mechanism (`cron` *cough*) to prune old data.

> Vendor inventory can differ slightly between players (vip-3 availability), how do we hanlde that?

I'd just hard-code the 3-day VIP case (server side) to not record these at all.

**Comment by traktofon** [comment]
Thanks for the answers @moritz. That all sounds good.

What would be a good name for the new API endpoints? According to the README there's documentation for the existing API in `API.md` but the file appears to be missing from the repository.

Is `v1/vendor-inventory/add` a reasonable choice for the API endpoint for submitting vendor inventory?

**Comment by moritz** [comment]
yes, your name suggestion is good.

Seems I don't have a local copy of `API.md` either, so I'll need to do some catch up on writing documentation :-(

**Comment by traktofon** [comment]
I've just pushed some initial update to the userscript for scraping and submitting vendor inventory (branch `items`).
Endpoint is as suggested, and the payload schematic is
```
{
  token: ,
  station: ,
  system: ,
  vendor: , 
  inventory: [
    {
      slug: ,
      price: ,
      currency: ,
    },
    ...
  ]
}
```
In principle the item category and name can be extracted as well, but seem redundant as the same data should be in the item database (eventually).

Example payload:
```
{"token":"(redacted)","station":"Yards of Gadani","system":"Alpha Centauri","vendor":"Al-Farooqi Gift Shop","inventory":[{"slug":"breakfast-knife","price":18300.61,"currency":"credits"},{"slug":"dull-tip-spark-phurba","price":10610.21,"currency":"credits"}, ... ]}
```

**Comment by moritz** [comment]
Looks good to me. Please also include `script_version` (as the tracker does in all write operations, to enable us to track which version of the user script people use).

**Comment by traktofon** [comment]
Ah yes, the script version is already included, as I use the `enrich_version` function.

**Comment by traktofon** [comment]
I've implemented scraping of item pages (currently in my own fork, will PR soon).

Example **Weapon** payload:
```
{
  "token":"...",
  "slug":"x35-wasp",
  "name":"X35 Wasp",
  "mass_kg":4.22,
  "rarity":"epic",
  "type":"Weapon",
  "tier":5,
  "desc":"A sleek and deadly design so branded due to the almost buzzing sound that accompanies its rapid fire projectiles.",
  "accuracy":0.24,
  "hand_to_hand":false,
  "long_range":true,
  "weapon_type":"Shotgun",
  "piercing_damage":31.34,
  "impact_damage":0,
  "energy_damage":0,
  "script_version":"1.10"
}
```

Example **Armor** payload:
```
{
  "token":"...",
  "slug":"magnus-burnshield",
  "name":"Magnus Burnshield",
  "mass_kg":7.49,
  "rarity":"epic",
  "type":"Armor",
  "tier":5,
  "desc":"A garment specifically designed to stand up to extreme heat, flames and explosives.",
  "piercing_defense":5.13,
  "impact_defense":14.17,
  "energy_defense":13.43,
  "script_version":"1.10"
}
```

Exaple **Medical** payload:
```
{
  "token":"...",
  "slug":"standard-stamina-stim-v3-2-004",
  "name":"Sta T02-V004-14.06-0.075",
  "mass_kg":0.03,
  "rarity":"uncommon",
  "type":"Medical",
  "tier":2,
  "desc":"A basic stamina stim.",
  "strength_boost":0,
  "agility_boost":0,
  "stamina_boost":14.06,
  "intelligence_boost":0,
  "social_boost":0,
  "base_toxicity_percent":7,
  "script_version":"1.10"
}
```

I've set up a local UTT instance and testing submission against that results in an error:
```
psycopg2.errors.UndefinedColumn: column item.rarity_id does not exist
```

**Comment by moritz** [comment]
The error seems to come from a column rename in commit 6308dfabe1320eadaf8fcc11215d11e350c0407c.

Try dropping the tables in question:

```sql
DROP TABLE IF EXISTS item_aspect_armor; 
DROP TABLE IF EXISTS item_aspect_weapon; 
DROP TABLE IF EXISTS item_aspect_medical; 
DROP TABLE IF EXISTS item_aspect_food; 
DROP TABLE IF EXISTS item; 
```

and then re-deploy these tables, for example by running `createuser.py moritz` or so (it re-creates the DB tables as a side effect).

**Comment by traktofon** [comment]
Ok, that worked. Thanks!

I see that the suggested weapon item API was changed from
```
"long_range":true,
```
to 
```
"range":"Long"
```

And some other things. I've wrote the userscript update before seeing the latest `API.md`.
I'll update the userscript. Edit: done and merged.

**Comment by moritz** [comment]
@traktofon update: the tracker now stores which vendor has which items available, but not yet their prices.

Also, there's currently no way yet to retrieve the data.

**Comment by moritz** [comment]
Update: prices are now stored as well.

**Comment by traktofon** [comment]
All implemented, so closing issue.
